apiVersion: apps/v1
kind: Deployment
metadata:
  name: kanban-app
spec:
  selector:
    matchLabels:
      app: kanban-app
  replicas: 2
  template:
    metadata:
      labels:
        app: kanban-app
    spec:
      containers:
      - name: kanban-app
        image: ritvikrc/kanban-app
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service 
metadata:
  name: kanban-app
spec:
  ports:
  - port: 8080 
    targetPort: 8080
  selector: 
    app: kanban-app