apiVersion: apps/v1
kind: Deployment
metadata:
  name: kanban-ui
spec:
  selector:
    matchLabels:
      app: kanban-ui
  replicas: 2
  template:
    metadata:
      labels:
        app: kanban-ui
    spec:
      containers:
      - name: kanban-ui
        image: ritvikrc/kanban-ui:working
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service 
metadata:
  name: kanban-ui
spec:
  type: LoadBalancer
  ports:
  - port: 80 
    targetPort: 80
    nodePort: 30321 
  selector: 
    app: kanban-ui